FROM apache/airflow:3.3.2

USER root

RUN apt-get update && \
    apt-get -y install git && \
    apt-get clean

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-microsoft-azure \
    apache-airflow-providers-ssh \
    apache-airflow-providers-common-sql \
    apache-airflow-providers-snowflake

