version: '3'

services:
  test:
    build:
      context: .
      dockerfile: dockerfile
    image: test:latest

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"
    command: airflow standalone