{{ config(materialized='view') }}

SELECT
    TRANSACTION_ID,
    CLIENT_ID,
    CLIENT_NAME,
    PORTFOLIO_ID,
    TICKER,
    TRANSACTION_TYPE,
    TRY_CAST(QUANTITY AS NUMBER(38, 4)) AS QUANTITY,
    TRY_CAST(PRICE AS NUMBER(38, 4)) AS PRICE,
    TRY_CAST(FEE_AMOUNT AS NUMBER(38, 4)) AS FEES,
    CURRENCY AS CURRENCY_CODE,
    TRY_CAST(TRANSACTION_TS AS TIMESTAMP_NTZ) AS TRANSACTION_TS,
    CAST(TRANSACTION_TS AS DATE) AS TRANSACTION_DATE,
    BATCH_ID,
    _LOADED_AT
FROM INVASIGHT.RAW.LEDGER_TRANSACTIONS_RAW
