{{ config(materialized='table') }}

SELECT
    MARKET_PRICE_KEY,
    DATE_KEY,
    ASSET_KEY,
    CURRENCY_KEY,
    SOURCE_KEY,
    CLOSE_PRICE,
    EXCHANGE_RATE,
    PRICE_SAR
FROM INVASIGHT.ANALYTICS.FACT_MARKET_PRICES
