{{ config(materialized='table') }}

SELECT
    HOLDING_KEY,
    DATE_KEY,
    ASSET_KEY,
    CLIENT_KEY,
    CURRENCY_KEY,
    TRANSACTION_TYPE,
    QUANTITY,
    PRICE,
    EXCHANGE_RATE,
    FEES,
    TRANSACTION_VALUE,
    VALUE_SAR
FROM INVASIGHT.ANALYTICS.FACT_HOLDINGS
