{{ config(materialized='table') }}

SELECT
    PORTFOLIO_SUMMARY_KEY,
    DATE_KEY,
    CLIENT_KEY,
    TOTAL_INVESTMENT,
    PORTFOLIO_VALUE_SAR,
    TOTAL_FEES,
    DAILY_RETURN,
    PNL_SAR,
    CURRENCY_EXPOSURE_SAR
FROM INVASIGHT.ANALYTICS.FACT_DAILY_PORTFOLIO_SUMMARY
